apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  #   local:
  #     push: false
  googleCloudBuild:
    projectId: soldout-dev
  artifacts:
    - image: us.gcr.io/soldout-dev/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
